stages:
  - build
  - deploy

build:
  stage: build
  image: atlassianlabs/docker-node-jdk-chrome-firefox
  variables:
    GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle
  script:
    - 'rm -rf frontend/node_modules'
    - './gradlew clean build'
  cache:
    paths:
      - '.gradle/wrapper'
      - '.gradle/caches'
  artifacts:
    paths:
      - 'build/distributions/'
    expire_in: 1 week
    when: on_success

deploy_demo:
  stage: deploy
  script:
    - './deploy/deploy.sh'
  environment: demo
  tags:
    - deploy
    - java8
  dependencies:
    - build
  only:
    - master
