server:
  type: simple
  applicationContextPath: /app
  adminContextPath: /admin
  rootPath: /api
  connector:
    type: http
    port: 8080

database:
  driverClass: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://localhost:3306/DB_DATABASE

  user: DB_USER
  password: DB_PASSWORD

  maxWaitForConnection: 1s
  validationQuery: "/* Teach4Service Health Check */ SELECT 1"
  validationQueryTimeout: 3s
  minSize: 4
  maxSize: 16
  checkConnectionWhileIdle: true
  evictionInterval: 10s

  properties:
    characterEncoding: UTF-8
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate.enable_lazy_load_no_trans: true

logging:
  level: INFO
  loggers:
#    "io.dropwizard": INFO
#    "org.hibernate.SQL":
#      level: DEBUG
    "org.hibernate.engine.internal":
      level: ERROR

auth:
  # the key used to encrypt the cookies
  cookieSecret: COOKIE_SECRET

  # number of seconds for an auth session to live. 1 hr by default.
  cookieAge: 3600

  systemUser:
    enabled: true
    password: ADMIN_PASSWORD

opentok:
  apiKey: 46010202
  secret: OT_SECRET
